### ISSUE TITLE
t/ltm.t fails with bleeding rakudo

### ISSUE THREAD

**Issue by gfldex** [jnthn/grammar-debugger#34]
```
1..1
ok 1 - grammar.parse(...) with the debugger works
1..1
Cannot look up attributes in a MyGrammar type object
  in regex test:sym<longest> at t/ltm.t line 15
  in block  at /home/dex/projekte/perl6/lib/grammar-debugger/lib/Grammar/Tracer.pm6 (Grammar::Tracer) line 47
  in regex test at t/ltm.t line 11
  in block  at /home/dex/projekte/perl6/lib/grammar-debugger/lib/Grammar/Tracer.pm6 (Grammar::Tracer) line 47
  in block <unit> at t/ltm.t line 31

# Looks like you planned 1 test, but ran 0
```

**Comment by jnthn** [comment]
I was going to blame it on the `uncurse` branch, for which I may well need to do some updates to this module. But it seems that isn't merged yet, so it's some unexpected Rakudo regression. If anybody has chance to bisect it, that'd be great. Otherwise, with `uncurse` imminent and going to need changes to this module anyway, I'll probably put it off some days and deal with the lot together.

**Comment by zoffixznet** [comment]
uncurse has now been merged, though this Issue was reported before that.

**Comment by gfldex** [comment]
seems alright now, closing this
